Add One Time Passcode Input
spear-ai/ui pull request #269
Opened 2024-05-30 16:56 UTC by ThomasSeaver

## Description

Creates a component for one time passcode input, based on a [primitive](https://input-otp.rodz.dev/). Mostly just took the examples and modified it to use our colors / patterns, used SVGs instead of divs, plus a little class modification since the outlines got weird. I skipped adding the carat because it felt awkward and I don't think it shows up in the current example, but I can add that if we feel like it's necessary beyond the highlighting.

Please let me know your opinion on the border / outline colors, I'm not sure there's an example in our library that handles anything quite like this yet, happy to set it to whatever. Also the name of the component itself I went back and forth on; if you have a preference that's not what I have here I'm happy to change that as well.

## Testing

Checkout the storybook, validate that it works

## Issues

- Closes #255

2024-05-31 10:53 UTC, psirenny commented
Will take a look ASAP.

2024-05-31 13:14 UTC, psirenny requested changes
Nicely done, left some comments.

2024-05-31 13:14 UTC, psirenny commented on packages/ui/src/components/one-time-passcode-input.tsx
> +      {character !== null && <div>{character}</div>}
Is the extra div required? I think I see it working without the wrapper.

2024-05-31 13:14 UTC, psirenny commented on packages/ui/src/components/one-time-passcode-input.tsx
> +    "border-neutral-a-7 outline-primary-8 group-focus-within:border-neutral-a-8 group-hover:border-neutral-a-8 relative flex h-14 w-10 items-center justify-center border-y text-2xl outline outline-0
Could we give the slots a subtle background color in light and dark mode? Something like `bg-white-a-3 dark:bg-black-a-3`.

2024-05-31 13:18 UTC, psirenny commented
@eakbulut @ThomasSeaver I went scouring Refero to see what others have done and happened upon these two examples which I thought were nice.

**Luma** (Surface input)
<img width="1475" alt="Screenshot 2024-05-31 at 9 15 34 AM" src="https://github.com/spear-ai/ui/assets/463178/377b4609-e0b6-4a7f-9f7c-d6924503eaab">

**Linktree* (Soft input)
<img width="1467" alt="Screenshot 2024-05-31 at 9 16 54 AM" src="https://github.com/spear-ai/ui/assets/463178/3746acb7-c27d-41ac-99d6-213da05b03e3">

Both of those have similar input variant styles as us: Soft and Surface. I also found Linktrees use of "0" as a placeholder very interesting. I don't know whether I love it or hate it 😛.

2024-05-31 13:46 UTC, ThomasSeaver commented on packages/ui/src/components/one-time-passcode-input.tsx
> +    "border-neutral-a-7 outline-primary-8 group-focus-within:border-neutral-a-8 group-hover:border-neutral-a-8 relative flex h-14 w-10 items-center justify-center border-y text-2xl outline outline-0
I'm fine with whatever you think is best; I was just following the example. One issue with outlines is I don't believe they have a right / left / top / bottom width control, so you end up with a thick inner wall on the slots like this: 
<img width="1068" alt="image" src="https://github.com/spear-ai/ui/assets/9162923/073e4f2e-0777-461c-9e26-8765f19609b8">
which is something the example was avoiding by controlling the borders, though it was a little janky

I agree that it clashes, but I also think this looks a little funky:
<img width="505" alt="image" src="https://github.com/spear-ai/ui/assets/9162923/0bfe367d-8961-40e9-bcc7-4b22009c4b50">
Is this what you were imagining, or something different?

2024-05-31 13:49 UTC, psirenny commented on packages/ui/src/components/one-time-passcode-input.tsx
> +    "border-neutral-a-7 outline-primary-8 group-focus-within:border-neutral-a-8 group-hover:border-neutral-a-8 relative flex h-14 w-10 items-center justify-center border-y text-2xl outline outline-0
Oh yea, that looks off. I think we'd need to make the the outline inset in that case. Can the offset be negative? `-outline-offset-px`

2024-05-31 17:54 UTC, psirenny approved these changes
Nice!

2024-05-31 18:34 UTC, eakbulut requested changes

2024-05-31 18:34 UTC, eakbulut commented on packages/ui/src/components/one-time-passcode-input.tsx
A couple of things:

- I think we need an error state when someone enters anything but a number, at the moment there is no feedback when the user does something wrong. Just turning the cell outline to red may suffice.

- Also related to the previous one; if I paste a 6 digit number it works fine. If I paste a 6 digit number with a hyphen in the middle, nothing happens. So, having a hyphen in the UI but not accepting an input with a hyphen is a bit conflicting. We should either remove the hyphen from the UI or disregard the hyphen and input rest of the code pasted without the hyphen or point out to the user that something is wrong.

- When I enter the code and want to go back to a specific digit to edit, it doesn't really work. When I click on first digit 3rd, 4rd or 6th digit gets the focus randomly.

- When I enter more than 6 digits, it keep updating the 6th digit with the extra numbers. e.g. If I accidentally enter `12345678`, I end up with `123458`. The focus should move away from 6th digit once it's filled.

2024-05-31 19:19 UTC, psirenny commented on packages/ui/src/components/one-time-passcode-input.tsx
👀 🥹

2024-06-03 09:51 UTC, psirenny commented
One thing I noticed also but I don't know if it requires addressing right away, is that the border between each slot should probably just be 1px instead of 2px. But I know that's complicated by the fact that we're using outlines with transparency.

2024-06-03 16:49 UTC, ThomasSeaver commented
> I think we need an error state when someone enters anything but a number, at the moment there is no feedback when the user does something wrong. Just turning the cell outline to red may suffice.

Should do this now for all non-numerics, besides a hyphen which it should silently swallow

> Also related to the previous one; if I paste a 6 digit number it works fine. If I paste a 6 digit number with a hyphen in the middle, nothing happens. So, having a hyphen in the UI but not accepting an input with a hyphen is a bit conflicting. We should either remove the hyphen from the UI or disregard the hyphen and input rest of the code pasted without the hyphen or point out to the user that something is wrong.

This should work now by disregarding the hyphen when pasted / input, though I did have to bastardize the primitive a tiny bit. As a side note, l'm not against a different pattern for the input. At this point I want to get it in, but if we wanted to revisit this with a spec in hand and remove the hyphen / alter the slot pattern I'd be okay with that. 

> When I enter the code and want to go back to a specific digit to edit, it doesn't really work. When I click on first digit; 3rd, 4rd or 6th digit gets the focus randomly.

This one is a real limitation of the base component, since the way its patterned is that its an invisible fake input underneath. I think pursuing a change here would be really pushing the boundaries of 'using' the component and also a can of worms, so I didn't go after it. It MIGHT be possible, but because the input ref is created inside the primitive and it has its own selection state, it concerns me.

> When I enter more than 6 digits, it keeps updating the 6th digit with the extra numbers. e.g. If I accidentally enter 12345678, I end up with 123458. The focus should move away from 6th digit once it's filled.

It should now not re-update the sixth digit. As a secondary bit I added a 'confirm' button to the story to show how an `onComplete` handler could shift the focus with refs, since I don't think it's a responsibility of the base input component. I also envision other patterns, like auto submitting the code, etc

> One thing I noticed also but I don't know if it requires addressing right away, is that the border between each slot should probably just be 1px instead of 2px. But I know that's complicated by the fact that we're using outlines with transparency.

yeah, like I mentioned earlier because the outline doesn't have sided controls AFAIK having an outline on each slot means that there's a thick inner wall. If you have a solution to that I'm happy to implement it but I wasn't sure what other option I had if we wanted to use outlines

2024-06-04 12:54 UTC, merged